project:
  type: website
  output-dir: docs

website:
  title: "EV Charger Blog"
  navbar:    
    right:
      - icon: github
        href: https://github.com/ShrutiSasi/ev-charger-blog

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    toc-title: "On this page"
    smooth-scroll: true
