project:
  type: website
  output-dir: docs

website:
  title: "EV Charger Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: posts/
    right:
      - icon: github
        href: https://github.com/ShrutiSasi/ev-charger-blog

format:
  html:
    theme: cosmo
